# Generated by Django 5.0.2 on 2024-03-01 03:13

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=355)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_client', models.BooleanField(default=True)),
                ('is_gallery', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Directory',
                'verbose_name_plural': 'Image Directory',
                'db_table': 'image_directory',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(blank=True, max_length=350, null=True)),
                ('title', models.TextField(blank=True, max_length=350, null=True)),
                ('meta_title', models.TextField(blank=True, max_length=350, null=True)),
                ('meta_keywords', models.TextField(blank=True, max_length=350, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=555, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'TOP_MENU')], default=portal.models.NAVIGATIONTYPE['TOP_MENU'])),
                ('menu', models.PositiveSmallIntegerField(choices=[(0, 'PAGE'), (1, 'BLOG'), (2, 'BLOG_DETAILS'), (3, 'SERVICES'), (4, 'SERVICES_DETAILS'), (5, 'GALLERY')], default=portal.models.MENUTYPE['PAGE'])),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=0)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.navigation')),
            ],
            options={
                'verbose_name': 'Navigation',
                'verbose_name_plural': 'Navigations',
                'db_table': 'navigation',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('image_position', models.PositiveSmallIntegerField(choices=[(0, 'NONE'), (1, 'LEFT'), (2, 'RIGHT')], default=portal.models.POSITION['NONE'])),
                ('title', models.CharField(max_length=355)),
                ('sub_title', models.CharField(max_length=355)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_html', models.BooleanField(default=True)),
                ('is_home', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('image_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.imagedirectory')),
                ('navigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.navigation')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('page_section', models.PositiveSmallIntegerField(choices=[(0, 'DEFAULT'), (1, 'SERVICE'), (2, 'BLOG'), (3, 'CLIENT'), (4, 'GALLERY'), (5, 'TESTIMOIALS')], default=portal.models.PAGESECTION['DEFAULT'])),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=355)),
                ('is_home', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('navigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.navigation')),
            ],
            options={
                'verbose_name': 'Pages',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='SectionDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('image_position', models.PositiveSmallIntegerField(choices=[(0, 'NONE'), (1, 'LEFT'), (2, 'RIGHT')], default=portal.models.POSITION['NONE'])),
                ('title', models.CharField(max_length=355)),
                ('sub_title', models.CharField(max_length=355)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_html', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('image_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.imagedirectory')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.pages')),
            ],
            options={
                'verbose_name': 'Section Default',
                'verbose_name_plural': 'Section Default',
                'db_table': 'section_default',
            },
        ),
        migrations.CreateModel(
            name='Testimoinals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=355)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_home', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('image_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.imagedirectory')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimoinals',
                'verbose_name_plural': 'Testimoinals',
                'db_table': 'testimoinals',
            },
        ),
    ]
