# Generated by Django 5.0.2 on 2024-03-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_features_packages_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='pice',
            new_name='price',
        ),
    ]
