# Generated by Django 5.0.2 on 2024-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_pice_packages_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='services',
            name='is_home',
            field=models.BooleanField(default=True),
        ),
    ]
