# Generated by Django 5.0.2 on 2024-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_services_sub_title_services_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pages',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pages',
            name='is_testimoinals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pages',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
