# Generated by Django 5.0.2 on 2025-02-04 05:37

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_pages_is_client_pages_is_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='menu',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PAGE'), (1, 'BLOG'), (2, 'SERVICES'), (3, 'GALLERY')], default=portal.models.MENUTYPE['PAGE']),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=250)),
                ('pet_type', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('pet_age', models.CharField(max_length=50)),
                ('aggressive', models.CharField(max_length=50)),
                ('vaccinations', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('location_link', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('banner_title', models.CharField(max_length=355)),
                ('banner_sub_title', models.CharField(max_length=355)),
                ('banner_content', models.TextField()),
                ('banner_image_one', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner_image_two', models.ImageField(blank=True, null=True, upload_to='')),
                ('use_layout_two', models.BooleanField(default=False)),
                ('fb_link', models.CharField(max_length=355)),
                ('x_link', models.CharField(max_length=355)),
                ('linkedin_link', models.CharField(max_length=355)),
                ('youtube_link', models.CharField(max_length=355)),
                ('instagram_link', models.CharField(max_length=355)),
                ('whatsapp_link', models.CharField(max_length=355)),
                ('name', models.TextField()),
                ('about_us', models.TextField()),
                ('email', models.TextField()),
                ('mobile', models.TextField()),
                ('address', models.TextField()),
                ('opening_hours', models.TextField()),
                ('email_to', models.CharField(blank=True, max_length=355, null=True)),
                ('email_cc', models.CharField(blank=True, max_length=355, null=True)),
                ('smtp_name', models.CharField(max_length=50)),
                ('smtp_host', models.CharField(max_length=20)),
                ('smtp_port', models.CharField(max_length=20)),
                ('smtp_username', models.CharField(max_length=200)),
                ('smtp_password', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
                'db_table': 'config',
            },
        ),
    ]
