# Generated by Django 5.0.2 on 2025-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='color_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='config',
            name='footer_script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='white_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
