# Generated by Django 5.0.2 on 2025-02-28 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_config_color_logo_config_footer_script_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('job_role', models.CharField(max_length=250)),
                ('job_type', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Career',
                'db_table': 'career',
            },
        ),
    ]
