# Generated by Django 5.0.2 on 2025-03-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='discount',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
